name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [g++, cl]
        build_type: [Debug, Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: martinlindhe/cmake-action@v2
        with:
          cmake-version: '3.21'

      - name: Run CMake configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}

      - name: Build with make
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Run tests
        run: ctest -C ${{ matrix.build_type }} -VV
